#!/usr/bin/env bash
# not found
sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" > '/var/www/html/index.nginx-debian.html'
sudo echo "Ceci n'est pas une pag" > '/var/www/html/404.html'
old_redirect='server_name _;'
new_redirect='server_name _;\n\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 /404.html'
sudo sed -i "s/'$old_redirect'/'$new_redirect'/" /etc/nginx/sites-available/default
sudo service nginx restart