#!/usr/bin/env bash
# Install haproxy and add load balancer
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*
new_redirect="frontend firstbalance\n\tbind *:80\n\tmode http\n\tdefault_backend webservers\n\nbackend webservers\n\tbalance roundrobin\n\tserver web-01 35.243.178.160:80 check\n\tserver web-02 35.243.142.199:80 check\n"
echo -e "$new_redirect" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
