#!/usr/bin/env bash
# Install haproxy and add load balancer
sudo apt-get update
sudo apt-get install haproxy=1.6.\*
new_redirect="
frontend firstbalance\n\t
    bind *:80\n\t
    mode http\n\t
    default_backend webservers\n\n
backend webservers\n\t
    balance roundrobin\n\t
    server 1666-web-01 35.243.178.160:80 check\n\t
    server 1666-web-02 35.243.142.199:80 check\n"
echo -e "$new_redirect" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
