#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and say hi in line 9
i=1
while [[ $i -lt 11 ]]; do
    echo "Holberton School"
    if ((i == 9)); then
        echo "Hi"
    fi
    i=$(( i+1 ))
done
