#!/usr/bin/env bash
# run nginx as nginx
sudo sed -i 's|80|8080|' /etc/nginx/sites-enabled/default
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
